# Generated by Django 3.2.7 on 2021-10-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_auto_20210930_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='courses',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
