# Generated by Django 3.2.7 on 2021-10-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0003_auto_20211001_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='position',
            field=models.CharField(choices=[('i', 'Instructor'), ('a', 'Assistent')], default='i', max_length=1),
            preserve_default=False,
        ),
    ]
